config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :invoices
  resources :staffs
  resources :inspections
  resources :halls
  resources :apartments
  resources :rooms
  resources :leases
  resources :parkings
  resources :vehicles
  resources :next_of_kins
  resources :instructors
  resources :courses
  resources :advisors
  resources :students
  get 'home/index'

  root 'home#index'

  get '/index', to: 'home#index'
  get '/student', to: 'students#index'
  get '/advisor', to: 'advisors#index'
  get '/course', to: 'courses#index'
  get '/instructor', to: 'instructors#index'
  get '/next_of_kin', to: 'next_of_kins#index'
  get '/vehicle', to: 'vehicles#index'
  get '/parking', to: 'parkings#index'
  get '/lease', to: 'leases#index'
  get '/room', to: 'rooms#index'
  get '/apartment', to: 'apartments#index'
  get '/hall', to: 'halls#index'
  get '/inspection', to: 'inspections#index'
  get '/staff', to: 'staffs#index'
  get '/invoice', to: 'invoices#index'
  get '/payment', to: 'payments#index'

  # query routes
  get '/query', to: 'query#index'
  get 'query/query1'
  get 'query/query2'
  get 'query/query3'
  get 'query/query4'
  get 'query/query5'
  get 'query/query6'
  get 'query/query7'
  get 'query/query8'
  get 'query/query9'
  get 'query/query10'
  get 'query/query11'
  get 'query/query12'
  get 'query/query13'
  get 'query/query14'
  get 'query/query15'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advisor.rb
class Advisor < ApplicationRecord
end

app/models/apartment.rb
class Apartment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/hall.rb
class Hall < ApplicationRecord
end

app/models/inspection.rb
class Inspection < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/lease.rb
class Lease < ApplicationRecord
end

app/models/next_of_kin.rb
class NextOfKin < ApplicationRecord
end

app/models/parking.rb
class Parking < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:staffFname, :staffLname, :staffStreet, :staffCity, :staffZip, :staffPhone, :staffEmail, :staffDoB, :staffGender, :staffPosition, :staffLocation, :staffPhone)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :staffFname %>
    <%= form.text_field :staffFname, id: :staff_staffFname %>
  </div>

  <div class="field">
    <%= form.label :staffLname %>
    <%= form.text_field :staffLname, id: :staff_staffLname %>
  </div>

  <div class="field">
    <%= form.label :staffStreet %>
    <%= form.text_field :staffStreet, id: :staff_staffStreet %>
  </div>

  <div class="field">
    <%= form.label :staffCity %>
    <%= form.text_field :staffCity, id: :staff_staffCity %>
  </div>

  <div class="field">
    <%= form.label :staffZip %>
    <%= form.number_field :staffZip, id: :staff_staffZip %>
  </div>

  <div class="field">
    <%= form.label :staffPhone %>
    <%= form.number_field :staffPhone, id: :staff_staffPhone %>
  </div>

  <div class="field">
    <%= form.label :staffEmail %>
    <%= form.text_field :staffEmail, id: :staff_staffEmail %>
  </div>

  <div class="field">
    <%= form.label :staffDoB %>
    <%= form.date_select :staffDoB, id: :staff_staffDoB %>
  </div>

  <div class="field">
    <%= form.label :staffGender %>
    <%= form.text_field :staffGender, id: :staff_staffGender %>
  </div>

  <div class="field">
    <%= form.label :staffPosition %>
    <%= form.text_field :staffPosition, id: :staff_staffPosition %>
  </div>

  <div class="field">
    <%= form.label :staffLocation %>
    <%= form.text_field :staffLocation, id: :staff_staffLocation %>
  </div>

  <div class="field">
    <%= form.label :staffPhone %>
    <%= form.number_field :staffPhone, id: :staff_staffPhone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Stafffname</th>
      <th>Stafflname</th>
      <th>Staffstreet</th>
      <th>Staffcity</th>
      <th>Staffzip</th>
      <th>Staffphone</th>
      <th>Staffemail</th>
      <th>Staffdob</th>
      <th>Staffgender</th>
      <th>Staffposition</th>
      <th>Stafflocation</th>
      <th>Staffphone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.staffFname %></td>
        <td><%= staff.staffLname %></td>
        <td><%= staff.staffStreet %></td>
        <td><%= staff.staffCity %></td>
        <td><%= staff.staffZip %></td>
        <td><%= staff.staffPhone %></td>
        <td><%= staff.staffEmail %></td>
        <td><%= staff.staffDoB %></td>
        <td><%= staff.staffGender %></td>
        <td><%= staff.staffPosition %></td>
        <td><%= staff.staffLocation %></td>
        <td><%= staff.staffPhone %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stafffname:</strong>
  <%= @staff.staffFname %>
</p>

<p>
  <strong>Stafflname:</strong>
  <%= @staff.staffLname %>
</p>

<p>
  <strong>Staffstreet:</strong>
  <%= @staff.staffStreet %>
</p>

<p>
  <strong>Staffcity:</strong>
  <%= @staff.staffCity %>
</p>

<p>
  <strong>Staffzip:</strong>
  <%= @staff.staffZip %>
</p>

<p>
  <strong>Staffphone:</strong>
  <%= @staff.staffPhone %>
</p>

<p>
  <strong>Staffemail:</strong>
  <%= @staff.staffEmail %>
</p>

<p>
  <strong>Staffdob:</strong>
  <%= @staff.staffDoB %>
</p>

<p>
  <strong>Staffgender:</strong>
  <%= @staff.staffGender %>
</p>

<p>
  <strong>Staffposition:</strong>
  <%= @staff.staffPosition %>
</p>

<p>
  <strong>Stafflocation:</strong>
  <%= @staff.staffLocation %>
</p>

<p>
  <strong>Staffphone:</strong>
  <%= @staff.staffPhone %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>