config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :invoices
  resources :staffs
  resources :inspections
  resources :halls
  resources :apartments
  resources :rooms
  resources :leases
  resources :parkings
  resources :vehicles
  resources :next_of_kins
  resources :instructors
  resources :courses
  resources :advisors
  resources :students
  get 'home/index'

  root 'home#index'

  get '/index', to: 'home#index'
  get '/student', to: 'students#index'
  get '/advisor', to: 'advisors#index'
  get '/course', to: 'courses#index'
  get '/instructor', to: 'instructors#index'
  get '/next_of_kin', to: 'next_of_kins#index'
  get '/vehicle', to: 'vehicles#index'
  get '/parking', to: 'parkings#index'
  get '/lease', to: 'leases#index'
  get '/room', to: 'rooms#index'
  get '/apartment', to: 'apartments#index'
  get '/hall', to: 'halls#index'
  get '/inspection', to: 'inspections#index'
  get '/staff', to: 'staffs#index'
  get '/invoice', to: 'invoices#index'
  get '/payment', to: 'payments#index'

  # query routes
  get '/query', to: 'query#index'
  get 'query/query1'
  get 'query/query2'
  get 'query/query3'
  get 'query/query4'
  get 'query/query5'
  get 'query/query6'
  get 'query/query7'
  get 'query/query8'
  get 'query/query9'
  get 'query/query10'
  get 'query/query11'
  get 'query/query12'
  get 'query/query13'
  get 'query/query14'
  get 'query/query15'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advisor.rb
class Advisor < ApplicationRecord
end

app/models/apartment.rb
class Apartment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/hall.rb
class Hall < ApplicationRecord
end

app/models/inspection.rb
class Inspection < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/lease.rb
class Lease < ApplicationRecord
end

app/models/next_of_kin.rb
class NextOfKin < ApplicationRecord
end

app/models/parking.rb
class Parking < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  before_action :set_hall, only: [:show, :edit, :update, :destroy]

  # GET /halls
  # GET /halls.json
  def index
    @halls = Hall.all
  end

  # GET /halls/1
  # GET /halls/1.json
  def show
  end

  # GET /halls/new
  def new
    @hall = Hall.new
  end

  # GET /halls/1/edit
  def edit
  end

  # POST /halls
  # POST /halls.json
  def create
    @hall = Hall.new(hall_params)

    respond_to do |format|
      if @hall.save
        format.html { redirect_to @hall, notice: 'Hall was successfully created.' }
        format.json { render :show, status: :created, location: @hall }
      else
        format.html { render :new }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /halls/1
  # PATCH/PUT /halls/1.json
  def update
    respond_to do |format|
      if @hall.update(hall_params)
        format.html { redirect_to @hall, notice: 'Hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @hall }
      else
        format.html { render :edit }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /halls/1
  # DELETE /halls/1.json
  def destroy
    @hall.destroy
    respond_to do |format|
      format.html { redirect_to halls_url, notice: 'Hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hall
      @hall = Hall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hall_params
      params.require(:hall).permit(:hallID, :hallCity, :hallStreet, :hallZip, :hallPhone, :managerID)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/halls/_form.html.erb
<%= form_with(model: hall, local: true) do |form| %>
  <% if hall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hall.errors.count, "error") %> prohibited this hall from being saved:</h2>

      <ul>
      <% hall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hallID %>
    <%= form.text_field :hallID, id: :hall_hallName %>
  </div>

  <div class="field">
    <%= form.label :hallCity %>
    <%= form.text_field :hallCity, id: :hall_hallCity %>
  </div>

  <div class="field">
    <%= form.label :hallStreet %>
    <%= form.text_field :hallStreet, id: :hall_hallStreet %>
  </div>

  <div class="field">
    <%= form.label :hallZip %>
    <%= form.number_field :hallZip, id: :hall_hallZip %>
  </div>

  <div class="field">
    <%= form.label :hallPhone %>
    <%= form.number_field :hallPhone, id: :hall_hallPhone %>
  </div>

  <div class="field">
    <%= form.label :managerID %>
    <%= form.number_field :managerID, id: :hall_managerID %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/halls/edit.html.erb
<h1>Editing Hall</h1>

<%= render 'form', hall: @hall %>

<%= link_to 'Show', @hall %> |
<%= link_to 'Back', halls_path %>

app/views/halls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Halls</h1>

<table>
  <thead>
    <tr>
      <th>Hallname</th>
      <th>Hallcity</th>
      <th>Hallstreet</th>
      <th>Hallzip</th>
      <th>Hallphone</th>
      <th>Managerid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @halls.each do |hall| %>
      <tr>
        <td><%= hall.hallName %></td>
        <td><%= hall.hallCity %></td>
        <td><%= hall.hallStreet %></td>
        <td><%= hall.hallZip %></td>
        <td><%= hall.hallPhone %></td>
        <td><%= hall.managerID %></td>
        <td><%= link_to 'Show', hall %></td>
        <td><%= link_to 'Edit', edit_hall_path(hall) %></td>
        <td><%= link_to 'Destroy', hall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hall', new_hall_path %>

app/views/halls/new.html.erb
<h1>New Hall</h1>

<%= render 'form', hall: @hall %>

<%= link_to 'Back', halls_path %>

app/views/halls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hallname:</strong>
  <%= @hall.hallName %>
</p>

<p>
  <strong>Hallcity:</strong>
  <%= @hall.hallCity %>
</p>

<p>
  <strong>Hallstreet:</strong>
  <%= @hall.hallStreet %>
</p>

<p>
  <strong>Hallzip:</strong>
  <%= @hall.hallZip %>
</p>

<p>
  <strong>Hallphone:</strong>
  <%= @hall.hallPhone %>
</p>

<p>
  <strong>Managerid:</strong>
  <%= @hall.managerID %>
</p>

<%= link_to 'Edit', edit_hall_path(@hall) %> |
<%= link_to 'Back', halls_path %>