config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :invoices
  resources :staffs
  resources :inspections
  resources :halls
  resources :apartments
  resources :rooms
  resources :leases
  resources :parkings
  resources :vehicles
  resources :next_of_kins
  resources :instructors
  resources :courses
  resources :advisors
  resources :students
  get 'home/index'

  root 'home#index'

  get '/index', to: 'home#index'
  get '/student', to: 'students#index'
  get '/advisor', to: 'advisors#index'
  get '/course', to: 'courses#index'
  get '/instructor', to: 'instructors#index'
  get '/next_of_kin', to: 'next_of_kins#index'
  get '/vehicle', to: 'vehicles#index'
  get '/parking', to: 'parkings#index'
  get '/lease', to: 'leases#index'
  get '/room', to: 'rooms#index'
  get '/apartment', to: 'apartments#index'
  get '/hall', to: 'halls#index'
  get '/inspection', to: 'inspections#index'
  get '/staff', to: 'staffs#index'
  get '/invoice', to: 'invoices#index'
  get '/payment', to: 'payments#index'

  # query routes
  get '/query', to: 'query#index'
  get 'query/query1'
  get 'query/query2'
  get 'query/query3'
  get 'query/query4'
  get 'query/query5'
  get 'query/query6'
  get 'query/query7'
  get 'query/query8'
  get 'query/query9'
  get 'query/query10'
  get 'query/query11'
  get 'query/query12'
  get 'query/query13'
  get 'query/query14'
  get 'query/query15'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advisor.rb
class Advisor < ApplicationRecord
end

app/models/apartment.rb
class Apartment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/hall.rb
class Hall < ApplicationRecord
end

app/models/inspection.rb
class Inspection < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/lease.rb
class Lease < ApplicationRecord
end

app/models/next_of_kin.rb
class NextOfKin < ApplicationRecord
end

app/models/parking.rb
class Parking < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:instructorFName, :instructorLName, :instructorEmail, :instructorPhone)
    end
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :instructorFName %>
    <%= form.text_field :instructorFName, id: :instructor_instructorFName %>
  </div>

  <div class="field">
    <%= form.label :instructorLName %>
    <%= form.text_field :instructorLName, id: :instructor_instructorLName %>
  </div>

  <div class="field">
    <%= form.label :instructorEmail %>
    <%= form.text_field :instructorEmail, id: :instructor_instructorEmail %>
  </div>

  <div class="field">
    <%= form.label :instructorPhone %>
    <%= form.number_field :instructorPhone, id: :instructor_instructorPhone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Instructorfname</th>
      <th>Instructorlname</th>
      <th>Instructoremail</th>
      <th>Instructorphone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.instructorFName %></td>
        <td><%= instructor.instructorLName %></td>
        <td><%= instructor.instructorEmail %></td>
        <td><%= instructor.instructorPhone %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instructorfname:</strong>
  <%= @instructor.instructorFName %>
</p>

<p>
  <strong>Instructorlname:</strong>
  <%= @instructor.instructorLName %>
</p>

<p>
  <strong>Instructoremail:</strong>
  <%= @instructor.instructorEmail %>
</p>

<p>
  <strong>Instructorphone:</strong>
  <%= @instructor.instructorPhone %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>