config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :invoices
  resources :staffs
  resources :inspections
  resources :halls
  resources :apartments
  resources :rooms
  resources :leases
  resources :parkings
  resources :vehicles
  resources :next_of_kins
  resources :instructors
  resources :courses
  resources :advisors
  resources :students
  get 'home/index'

  root 'home#index'

  get '/index', to: 'home#index'
  get '/student', to: 'students#index'
  get '/advisor', to: 'advisors#index'
  get '/course', to: 'courses#index'
  get '/instructor', to: 'instructors#index'
  get '/next_of_kin', to: 'next_of_kins#index'
  get '/vehicle', to: 'vehicles#index'
  get '/parking', to: 'parkings#index'
  get '/lease', to: 'leases#index'
  get '/room', to: 'rooms#index'
  get '/apartment', to: 'apartments#index'
  get '/hall', to: 'halls#index'
  get '/inspection', to: 'inspections#index'
  get '/staff', to: 'staffs#index'
  get '/invoice', to: 'invoices#index'
  get '/payment', to: 'payments#index'

  # query routes
  get '/query', to: 'query#index'
  get 'query/query1'
  get 'query/query2'
  get 'query/query3'
  get 'query/query4'
  get 'query/query5'
  get 'query/query6'
  get 'query/query7'
  get 'query/query8'
  get 'query/query9'
  get 'query/query10'
  get 'query/query11'
  get 'query/query12'
  get 'query/query13'
  get 'query/query14'
  get 'query/query15'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advisor.rb
class Advisor < ApplicationRecord
end

app/models/apartment.rb
class Apartment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/hall.rb
class Hall < ApplicationRecord
end

app/models/inspection.rb
class Inspection < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/lease.rb
class Lease < ApplicationRecord
end

app/models/next_of_kin.rb
class NextOfKin < ApplicationRecord
end

app/models/parking.rb
class Parking < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:apartmentCity, :apartmentStreet, :apartmentZip, :apartmentNumOfRooms)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :apartmentCity %>
    <%= form.text_field :apartmentCity, id: :apartment_apartmentCity %>
  </div>

  <div class="field">
    <%= form.label :apartmentStreet %>
    <%= form.text_field :apartmentStreet, id: :apartment_apartmentStreet %>
  </div>

  <div class="field">
    <%= form.label :apartmentZip %>
    <%= form.number_field :apartmentZip, id: :apartment_apartmentZip %>
  </div>

  <div class="field">
    <%= form.label :apartmentNumOfRooms %>
    <%= form.number_field :apartmentNumOfRooms, id: :apartment_apartmentNumOfRooms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Apartmentcity</th>
      <th>Apartmentstreet</th>
      <th>Apartmentzip</th>
      <th>Apartmentnumofrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.apartmentCity %></td>
        <td><%= apartment.apartmentStreet %></td>
        <td><%= apartment.apartmentZip %></td>
        <td><%= apartment.apartmentNumOfRooms %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apartmentcity:</strong>
  <%= @apartment.apartmentCity %>
</p>

<p>
  <strong>Apartmentstreet:</strong>
  <%= @apartment.apartmentStreet %>
</p>

<p>
  <strong>Apartmentzip:</strong>
  <%= @apartment.apartmentZip %>
</p>

<p>
  <strong>Apartmentnumofrooms:</strong>
  <%= @apartment.apartmentNumOfRooms %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>